//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Ogrenci_Kayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public int OgrenciID { get; set; }
        public string OgrenciAd { get; set; }
        public string OgrenciSoyad { get; set; }
        public string OgrenciEMail { get; set; }
        public string OgrenciImage { get; set; }
        public string OgrenciAdres { get; set; }
    }
}
